-- Discord Emoji Bridge module for OTClient
-- Converts Discord shortcodes (:smile:) <-> text emoticons / Unicode emojis
-- Since OTClient uses bitmap fonts by default, text emoticons are used as fallback

-- Configuration: set to true to use Unicode emojis (requires TTF font with emoji support)
-- Set to false to use text emoticons (works with bitmap fonts)
local USE_UNICODE_EMOJIS = false

-- Discord shortcode -> (text emoticon, unicode emoji)
DiscordEmojis = {
    -- Faces - positive
    [":smile:"] = {":)", "\xF0\x9F\x98\x84"},
    [":grinning:"] = {":D", "\xF0\x9F\x98\x80"},
    [":smiley:"] = {":D", "\xF0\x9F\x98\x83"},
    [":laughing:"] = {":D", "\xF0\x9F\x98\x86"},
    [":joy:"] = {"xD", "\xF0\x9F\x98\x82"},
    [":rofl:"] = {"xD", "\xF0\x9F\xA4\xA3"},
    [":wink:"] = {";)", "\xF0\x9F\x98\x89"},
    [":blush:"] = {":)", "\xF0\x9F\x98\x8A"},
    [":slight_smile:"] = {":)", "\xF0\x9F\x99\x82"},
    [":upside_down:"] = {"(:", "\xF0\x9F\x99\x83"},
    [":relaxed:"] = {":)", "\xF0\x9F\x98\x8C"},
    [":yum:"] = {":)", "\xF0\x9F\x98\x8B"},
    [":heart_eyes:"] = {"<3", "\xF0\x9F\x98\x8D"},
    [":kissing_heart:"] = {"<3", "\xF0\x9F\x98\x98"},
    [":kissing:"] = {":*", "\xF0\x9F\x98\x97"},
    [":kissing_smiling_eyes:"] = {";*", "\xF0\x9F\x98\x99"},
    [":stuck_out_tongue:"] = {":p", "\xF0\x9F\x98\x9B"},
    [":stuck_out_tongue_winking_eye:"] = {";p", "\xF0\x9F\x98\x9C"},
    [":stuck_out_tongue_closed_eyes:"] = {"xp", "\xF0\x9F\x98\x9D"},
    [":nerd:"] = {"8)", "\xF0\x9F\xA4\x93"},
    [":sunglasses:"] = {"8)", "\xF0\x9F\x98\x8E"},
    [":star_struck:"] = {":D", "\xF0\x9F\xA4\xA9"},
    [":zany_face:"] = {":D", "\xF0\x9F\xA4\xAA"},
    [":shushing_face:"] = {":)", "\xF0\x9F\xA4\xAB"},
    [":thinking:"] = {":|", "\xF0\x9F\xA4\x94"},
    [":hand_over_mouth:"] = {":)", "\xF0\x9F\xA4\xAD"},
    [":smiling_face_with_tear:"] = {":')", "\xF0\x9F\xA5\xB9"},
    [":pleading_face:"] = {":(", "\xF0\x9F\xA5\xBA"},
    [":smirk:"] = {":)", "\xF0\x9F\x98\x8F"},
    [":unamused:"] = {":|", "\xF0\x9F\x98\x92"},
    [":rolling_eyes:"] = {":|", "\xF0\x9F\x99\x84"},
    [":relieved:"] = {":)", "\xF0\x9F\x98\x8C"},
    [":pensive:"] = {":(", "\xF0\x9F\x98\x94"},
    [":sleepy:"] = {"-_-", "\xF0\x9F\x98\xAA"},
    [":drooling_face:"] = {":)", "\xF0\x9F\xA4\xA4"},
    [":sleeping:"] = {"zzz", "\xF0\x9F\x98\xB4"},
    [":mask:"] = {":)", "\xF0\x9F\x98\xB7"},
    [":face_with_thermometer:"] = {":(", "\xF0\x9F\xA4\x92"},
    [":face_with_head_bandage:"] = {":(", "\xF0\x9F\xA4\x95"},
    [":nauseated_face:"] = {":(", "\xF0\x9F\xA4\xAE"},
    [":sneezing_face:"] = {":)", "\xF0\x9F\xA4\xA7"},
    [":dizzy_face:"] = {"x_x", "\xF0\x9F\x98\xB5"},
    [":cowboy:"] = {":)", "\xF0\x9F\xA4\xA0"},
    [":disguised_face:"] = {":)", "\xF0\x9F\xA5\xB8"},

    -- Faces - negative
    [":frowning:"] = {":(", "\xF0\x9F\x98\xA6"},
    [":anguished:"] = {":(", "\xF0\x9F\x98\xA7"},
    [":open_mouth:"] = {":o", "\xF0\x9F\x98\xAE"},
    [":astonished:"] = {":o", "\xF0\x9F\x98\xB2"},
    [":confounded:"] = {"x_x", "\xF0\x9F\x98\x96"},
    [":worried:"] = {":(", "\xF0\x9F\x98\x9F"},
    [":fearful:"] = {":(", "\xF0\x9F\x98\xA8"},
    [":cold_sweat:"] = {":(", "\xF0\x9F\x98\xB0"},
    [":disappointed:"] = {":(", "\xF0\x9F\x98\x9E"},
    [":cry:"] = {":'(", "\xF0\x9F\x98\xA2"},
    [":sob:"] = {":'(", "\xF0\x9F\x98\xAD"},
    [":sweat:"] = {":)", "\xF0\x9F\x98\x85"},
    [":weary:"] = {":(", "\xF0\x9F\x98\xA9"},
    [":triumph:"] = {">:(", "\xF0\x9F\x98\xA4"},
    [":angry:"] = {">:(", "\xF0\x9F\x98\xA0"},
    [":rage:"] = {">:(", "\xF0\x9F\x98\xA1"},
    [":symbols_over_mouth:"] = {">:(", "\xF0\x9F\xA4\xAC"},
    [":confused:"] = {":s", "\xF0\x9F\x98\x95"},
    [":hushed:"] = {":o", "\xF0\x9F\x98\xAF"},
    [":no_mouth:"] = {":|", "\xF0\x9F\x98\xB6"},
    [":neutral_face:"] = {":|", "\xF0\x9F\x98\x90"},
    [":expressionless:"] = {":|", "\xF0\x9F\x98\x91"},
    [":grimacing:"] = {":|", "\xF0\x9F\x98\xAC"},
    [":face_with_raised_eyebrow:"] = {":|", "\xF0\x9F\xA4\xA8"},

    -- Gestures
    [":+1:"] = {"(y)", "\xF0\x9F\x91\x8D"},
    [":thumbsup:"] = {"(y)", "\xF0\x9F\x91\x8D"},
    [":-1:"] = {"(n)", "\xF0\x9F\x91\x8E"},
    [":thumbsdown:"] = {"(n)", "\xF0\x9F\x91\x8E"},
    [":ok_hand:"] = {"(ok)", "\xF0\x9F\x91\x8C"},
    [":v:"] = {"(v)", "\xE2\x9C\x8C"},
    [":wave:"] = {"(wave)", "\xF0\x9F\x91\x8B"},
    [":clap:"] = {"(clap)", "\xF0\x9F\x91\x8F"},
    [":hand:"] = {"(stop)", "\xE2\x9C\x8B"},
    [":raised_hand:"] = {"(stop)", "\xE2\x9C\x8B"},
    [":pray:"] = {"(pray)", "\xF0\x9F\x99\x8F"},
    [":point_up:"] = {"(up)", "\xF0\x9F\x91\x86"},
    [":point_down:"] = {"(down)", "\xF0\x9F\x91\x87"},
    [":point_left:"] = {"(left)", "\xF0\x9F\x91\x88"},
    [":point_right:"] = {"(right)", "\xF0\x9F\x91\x89"},
    [":point_forward:"] = {"(fwd)", "\xF0\x9F\x91\x89"},
    [":muscle:"] = {"(flex)", "\xF0\x9F\x92\xAA"},
    [":fist:"] = {"(fist)", "\xE2\x9C\x8A"},
    [":punch:"] = {"(punch)", "\xF0\x9F\x91\x8A"},
    [":handshake:"] = {"(shake)", "\xF0\x9F\xA4\x9D"},
    [":peace:"] = {"(peace)", "\xE2\x9C\x8C"},

    -- Hearts and symbols
    [":heart:"] = {"<3", "\xE2\x9D\xA4"},
    [":hearts:"] = {"<3", "\xE2\x9D\xA4\xEF\xB8\x8F\xF0\x9F\x92\x9D"},
    [":orange_heart:"] = {"<3", "\xF0\x9F\xA7\xA1"},
    [":yellow_heart:"] = {"<3", "\xF0\x9F\x92\x9B"},
    [":green_heart:"] = {"<3", "\xF0\x9F\x92\x9A"},
    [":blue_heart:"] = {"<3", "\xF0\x9F\x92\x99"},
    [":purple_heart:"] = {"<3", "\xF0\x9F\x92\x9C"},
    [":black_heart:"] = {"<3", "\xF0\x9F\x96\xA4"},
    [":broken_heart:"] = {"</3", "\xF0\x9F\x92\x94"},
    [":heart_exclamation:"] = {"<3!", "\xE2\x9D\xA3"},
    [":two_hearts:"] = {"<3", "\xF0\x9F\x92\x95"},
    [":revolving_hearts:"] = {"<3", "\xF0\x9F\x92\x9E"},
    [":heartbeat:"] = {"<3", "\xF0\x9F\x92\x93"},
    [":sparkling_heart:"] = {"<3", "\xF0\x9F\x92\x96"},
    [":cupid:"] = {"<3", "\xF0\x9F\x92\x98"},
    [":gift_heart:"] = {"<3", "\xF0\x9F\x8E\x81"},
    [":star:"] = {"*", "\xE2\xAD\x90"},
    [":star2:"] = {"*", "\xF0\x9F\x8C\x9F"},
    [":sparkles:"] = {"*", "\xE2\x9C\xA8"},
    [":dizzy:"] = {"*", "\xF0\x9F\x92\xAB"},
    [":boom:"] = {"(boom)", "\xF0\x9F\x92\xA5"},
    [":anger:"] = {">:(", "\xF0\x9F\x92\xA2"},
    [":sweat_drops:"] = {"(sweat)", "\xF0\x9F\x92\xA6"},
    [":dash:"] = {"(dash)", "\xF0\x9F\x92\xA8"},
    [":hole:"] = {"(hole)", "\xF0\x9F\x95\xB3"},
    [":bomb:"] = {"(bomb)", "\xF0\x9F\x92\xA3"},
    [":zzz:"] = {"zzz", "\xF0\x9F\x92\xA4"},
    [":100:"] = {"100%", "\xF0\x9F\x92\xAF"},
    [":fire:"] = {"(fire)", "\xF0\x9F\x94\xA5"},
    [":rocket:"] = {"(rocket)", "\xF0\x9F\x9A\x80"},
    [":white_check_mark:"] = {"(ok)", "\xE2\x9C\x85"},
    [":x:"] = {"(x)", "\xE2\x9D\x8C"},
    [":no_entry:"] = {"(no)", "\xE2\x9B\x94"},
    [":no_entry_sign:"] = {"(no)", "\xF0\x9F\x9A\xAB"},
    [":warning:"] = {"(!)", "\xE2\x9A\xA0"},
    [":question:"] = {"?", "\xE2\x9D\x93"},
    [":exclamation:"] = {"!", "\xE2\x9D\x97"},
    [":heavy_exclamation_mark:"] = {"!", "\xE2\x9D\x97"},
    [":grey_exclamation:"] = {"!", "\xE2\x9D\x95"},
    [":grey_question:"] = {"?", "\xE2\x9D\x94"},

    -- Objects
    [":coffee:"] = {"(coffee)", "\xE2\x98\x95"},
    [":tea:"] = {"(tea)", "\xF0\x9F\x8D\xB5"},
    [":beer:"] = {"(beer)", "\xF0\x9F\x8D\xBA"},
    [":beers:"] = {"(beer)", "\xF0\x9F\x8D\xBB"},
    [":wine_glass:"] = {"(wine)", "\xF0\x9F\x8D\xB7"},
    [":tropical_drink:"] = {"(drink)", "\xF0\x9F\x8D\xB9"},
    [":pizza:"] = {"(pizza)", "\xF0\x9F\x8D\x95"},
    [":burger:"] = {"(burger)", "\xF0\x9F\x8D\x94"},
    [":cake:"] = {"(cake)", "\xF0\x9F\x8D\xB0"},
    [":icecream:"] = {"(ice)", "\xF0\x9F\x8D\xA6"},
    [":cookie:"] = {"(cookie)", "\xF0\x9F\x8D\xAA"},
    [":apple:"] = {"(apple)", "\xF0\x9F\x8D\x8E"},
    [":taco:"] = {"(taco)", "\xF0\x9F\x8C\xAE"},
    [":moneybag:"] = {"($)", "\xF0\x9F\x92\xB0"},
    [":dollar:"] = {"($)", "\xF0\x9F\x92\xB5"},
    [":gem:"] = {"(gem)", "\xF0\x9F\x92\x8E"},
    [":crown:"] = {"(crown)", "\xF0\x9F\x91\x91"},
    [":trophy:"] = {"(trophy)", "\xF0\x9F\x8F\x86"},
    [":medal:"] = {"(medal)", "\xF0\x9F\x8E\x96"},
    [":shield:"] = {"(shield)", "\xF0\x9F\x9B\xA1"},
    [":sword:"] = {"(sword)", "\xE2\x9A\x94"},
    [":bow_and_arrow:"] = {"(bow)", "\xF0\x9F\x8F\xB9"},
    [":skull:"] = {"(skull)", "\xF0\x9F\x92\x80"},
    [":skull_crossbones:"] = {"(skull)", "\xE2\x98\xA0"},
    [":ghost:"] = {"(ghost)", "\xF0\x9F\x91\xBB"},
    [":jack_o_lantern:"] = {"(pumpkin)", "\xF0\x9F\x8E\x83"},
    [":alien:"] = {"(alien)", "\xF0\x9F\x91\xBD"},
    [":robot:"] = {"(robot)", "\xF0\x9F\xA4\x96"},
    [":video_game:"] = {"(game)", "\xF0\x9F\x8E\xAE"},
    [":game_controller:"] = {"(game)", "\xF0\x9F\x8E\xAE"},
    [":dice:"] = {"(dice)", "\xF0\x9F\x8E\xB2"},
    [":musical_note:"] = {"(note)", "\xF0\x9F\x8E\xB5"},
    [":notes:"] = {"(music)", "\xF0\x9F\x8E\xB6"},
    [":headphones:"] = {"(music)", "\xF0\x9F\x8E\xA7"},

    -- Nature
    [":sunny:"] = {"(sun)", "\xE2\x98\x80"},
    [":moon:"] = {"(moon)", "\xF0\x9F\x8C\x94"},
    [":full_moon:"] = {"(moon)", "\xF0\x9F\x8C\x95"},
    [":crescent_moon:"] = {"(moon)", "\xF0\x9F\x8C\x99"},
    [":cloud:"] = {"(cloud)", "\xE2\x98\x81"},
    [":rainbow:"] = {"(rainbow)", "\xF0\x9F\x8C\x88"},
    [":fire:"] = {"(fire)", "\xF0\x9F\x94\xA5"},
    [":snowflake:"] = {"(snow)", "\xE2\x9D\x84"},
    [":zap:"] = {"(zap)", "\xE2\x9A\xA1"},
    [":umbrella:"] = {"(rain)", "\xE2\x98\x82"},
    [":ocean:"] = {"(wave)", "\xF0\x9F\x8C\x8A"},
    [":tulip:"] = {"(flower)", "\xF0\x9F\x8C\xB7"},
    [":rose:"] = {"(rose)", "\xF0\x9F\x8C\xB9"},
    [":sunflower:"] = {"(flower)", "\xF0\x9F\x8C\xBB"},
    [":cherry_blossom:"] = {"(flower)", "\xF0\x9F\x8C\xB8"},
    [":cactus:"] = {"(cactus)", "\xF0\x9F\x8C\xB5"},
    [":tree:"] = {"(tree)", "\xF0\x9F\x8C\xB3"},
    [":evergreen_tree:"] = {"(tree)", "\xF0\x9F\x8C\xB2"},
    [":palm_tree:"] = {"(palm)", "\xF0\x9F\x8C\xB4"},
    [":maple_leaf:"] = {"(leaf)", "\xF0\x9F\x8D\x81"},
    [":leaves:"] = {"(leaf)", "\xF0\x9F\x8D\x83"},
    [":mushroom:"] = {"(mushroom)", "\xF0\x9F\x8D\x84"},
    [":earth_africa:"] = {"(earth)", "\xF0\x9F\x8C\x8D"},
    [":earth_americas:"] = {"(earth)", "\xF0\x9F\x8C\x8E"},
    [":earth_asia:"] = {"(earth)", "\xF0\x9F\x8C\x8F"},

    -- Animals
    [":dog:"] = {"(dog)", "\xF0\x9F\x90\xB6"},
    [":cat:"] = {"(cat)", "\xF0\x9F\x90\xB1"},
    [":mouse:"] = {"(mouse)", "\xF0\x9F\x90\xAD"},
    [":hamster:"] = {"(hamster)", "\xF0\x9F\x90\xB9"},
    [":rabbit:"] = {"(rabbit)", "\xF0\x9F\x90\xB0"},
    [":fox:"] = {"(fox)", "\xF0\x9F\xA6\x8A"},
    [":bear:"] = {"(bear)", "\xF0\x9F\x90\xBB"},
    [":panda:"] = {"(panda)", "\xF0\x9F\x90\xBC"},
    [":koala:"] = {"(koala)", "\xF0\x9F\x90\xA8"},
    [":tiger:"] = {"(tiger)", "\xF0\x9F\x90\xAF"},
    [":lion:"] = {"(lion)", "\xF0\x9F\xA6\x81"},
    [":cow:"] = {"(cow)", "\xF0\x9F\x90\xAE"},
    [":pig:"] = {"(pig)", "\xF0\x9F\x90\xB7"},
    [":frog:"] = {"(frog)", "\xF0\x9F\x90\xB8"},
    [":monkey:"] = {"(monkey)", "\xF0\x9F\x90\xB5"},
    [":chicken:"] = {"(chicken)", "\xF0\x9F\x90\x94"},
    [":penguin:"] = {"(penguin)", "\xF0\x9F\x90\xA7"},
    [":bird:"] = {"(bird)", "\xF0\x9F\x90\xA6"},
    [":duck:"] = {"(duck)", "\xF0\x9F\xA6\x86"},
    [":owl:"] = {"(owl)", "\xF0\x9F\xA6\x89"},
    [":bat:"] = {"(bat)", "\xF0\x9F\xA6\x87"},
    [":wolf:"] = {"(wolf)", "\xF0\x9F\x90\xBA"},
    [":boar:"] = {"(boar)", "\xF0\x9F\x90\x97"},
    [":horse:"] = {"(horse)", "\xF0\x9F\x90\xB4"},
    [":unicorn:"] = {"(unicorn)", "\xF0\x9F\xA6\x84"},
    [":bee:"] = {"(bee)", "\xF0\x9F\x90\x9D"},
    [":bug:"] = {"(bug)", "\xF0\x9F\x90\x9B"},
    [":butterfly:"] = {"(butterfly)", "\xF0\x9F\xA6\x8B"},
    [":snail:"] = {"(snail)", "\xF0\x9F\x90\x8C"},
    [":snake:"] = {"(snake)", "\xF0\x9F\x90\x8D"},
    [":turtle:"] = {"(turtle)", "\xF0\x9F\x90\xA2"},
    [":dragon:"] = {"(dragon)", "\xF0\x9F\x90\x89"},
    [":dragon_face:"] = {"(dragon)", "\xF0\x9F\x90\xB2"},
    [":whale:"] = {"(whale)", "\xF0\x9F\x90\xB3"},
    [":dolphin:"] = {"(dolphin)", "\xF0\x9F\x90\xAC"},
    [":fish:"] = {"(fish)", "\xF0\x9F\x90\x9F"},
    [":tropical_fish:"] = {"(fish)", "\xF0\x9F\x90\xA0"},
    [":blowfish:"] = {"(fish)", "\xF0\x9F\x90\xA1"},
    [":octopus:"] = {"(octopus)", "\xF0\x9F\x90\x99"},
    [":crab:"] = {"(crab)", "\xF0\x9F\xA6\x80"},
    [":shrimp:"] = {"(shrimp)", "\xF0\x9F\xA6\x90"},
    [":squid:"] = {"(squid)", "\xF0\x9F\xA6\x91"},

    -- Activities
    [":soccer:"] = {"(soccer)", "\xE2\x9A\xBD"},
    [":basketball:"] = {"(basketball)", "\xF0\x9F\x8F\x80"},
    [":football:"] = {"(football)", "\xF0\x9F\x8F\x88"},
    [":baseball:"] = {"(baseball)", "\xE2\x9A\xBE"},
    [":tennis:"] = {"(tennis)", "\xF0\x9F\x8E\xBE"},
    [":8ball:"] = {"(8ball)", "\xF0\x9F\x8E\xB1"},
    [":bowling:"] = {"(bowling)", "\xF0\x9F\x8E\xB3"},
    [":dart:"] = {"(dart)", "\xF0\x9F\x8E\xAF"},
    [":video_game:"] = {"(game)", "\xF0\x9F\x8E\xAE"},
    [":slot_machine:"] = {"(slot)", "\xF0\x9F\x8E\xB0"},
    [":game_die:"] = {"(dice)", "\xF0\x9F\x8E\xB2"},
    [":spades:"] = {"(spades)", "\xE2\x99\xA0"},
    [":hearts:"] = {"<3", "\xE2\x99\xA5"},
    [":diamonds:"] = {"(diamonds)", "\xE2\x99\xA6"},
    [":clubs:"] = {"(clubs)", "\xE2\x99\xA3"},
    [":black_joker:"] = {"(joker)", "\xF0\x9F\x83\x8F"},
    [":mahjong:"] = {"(mahjong)", "\xF0\x9F\x80\x84"},
    [":musical_keyboard:"] = {"(piano)", "\xF0\x9F\x8E\xB9"},
    [":guitar:"] = {"(guitar)", "\xF0\x9F\x8E\xB8"},
    [":violin:"] = {"(violin)", "\xF0\x9F\x8E\xBB"},
    [":drum:"] = {"(drum)", "\xF0\x9F\xA5\x81"},
    [":saxophone:"] = {"(sax)", "\xF0\x9F\x8E\xB7"},
    [":trumpet:"] = {"(trumpet)", "\xF0\x9F\x8E\xBA"},

    -- Travel
    [":car:"] = {"(car)", "\xF0\x9F\x9A\x97"},
    [":red_car:"] = {"(car)", "\xF0\x9F\x9A\x97"},
    [":taxi:"] = {"(taxi)", "\xF0\x9F\x9A\x95"},
    [":bus:"] = {"(bus)", "\xF0\x9F\x9A\x8D"},
    [":trolleybus:"] = {"(bus)", "\xF0\x9F\x9A\x8E"},
    [":race_car:"] = {"(car)", "\xF0\x9F\x8F\x8E"},
    [":motorcycle:"] = {"(moto)", "\xF0\x9F\x8F\x8D"},
    [":bike:"] = {"(bike)", "\xF0\x9F\x9A\xB2"},
    [":train:"] = {"(train)", "\xF0\x9F\x9A\x8B"},
    [":metro:"] = {"(metro)", "\xF0\x9F\x9A\x87"},
    [":airplane:"] = {"(plane)", "\xE2\x9C\x88"},
    [":helicopter:"] = {"(heli)", "\xF0\x9F\x9A\x81"},
    [":rocket:"] = {"(rocket)", "\xF0\x9F\x9A\x80"},
    [":ship:"] = {"(ship)", "\xF0\x9F\x9A\xA2"},
    [":sailboat:"] = {"(boat)", "\xE2\x9B\xB5"},
    [":anchor:"] = {"(anchor)", "\xE2\x9A\x93"},
    [":fuelpump:"] = {"(fuel)", "\xE2\x9B\xBD"},
    [":construction:"] = {"(work)", "\xF0\x9F\x9A\xA7"},
    [":house:"] = {"(house)", "\xF0\x9F\x8F\xA0"},
    [":house_with_garden:"] = {"(house)", "\xF0\x9F\x8F\xA1"},
    [":school:"] = {"(school)", "\xF0\x9F\x8F\xAB"},
    [":hospital:"] = {"(hospital)", "\xF0\x9F\x8F\xA5"},
    [":bank:"] = {"(bank)", "\xF0\x9F\x8F\xA6"},
    [":hotel:"] = {"(hotel)", "\xF0\x9F\x8F\xA8"},
    [":church:"] = {"(church)", "\xE2\x9B\xAA"},
    [":castle:"] = {"(castle)", "\xF0\x9F\x8F\xB0"},
    [":statue_of_liberty:"] = {"(liberty)", "\xF0\x9F\x97\xBD"},
    [":tokyo_tower:"] = {"(tower)", "\xF0\x9F\x97\xBC"},
    [":fountain:"] = {"(fountain)", "\xE2\x9B\xB2"},
    [":tent:"] = {"(tent)", "\xE2\x9B\xBA"},
    [":foggy:"] = {"(fog)", "\xF0\x9F\x8C\xAB"},
    [":night_with_stars:"] = {"(night)", "\xF0\x9F\x8C\x83"},
    [":sunrise:"] = {"(sunrise)", "\xF0\x9F\x8C\x84"},
    [":sunrise_over_mountains:"] = {"(sunrise)", "\xF0\x9F\x8C\x85"},
    [":city_sunset:"] = {"(sunset)", "\xF0\x9F\x8C\x86"},
    [":city_dusk:"] = {"(dusk)", "\xF0\x9F\x8C\x87"},

    -- Symbols
    [":white_circle:"] = {"(o)", "\xE2\x9A\xAA"},
    [":black_circle:"] = {"(x)", "\xE2\x9A\xAB"},
    [":red_circle:"] = {"(o)", "\xF0\x9F\x94\xB4"},
    [":large_blue_circle:"] = {"(o)", "\xF0\x9F\x94\xB5"},
    [":large_blue_diamond:"] = {"(diamond)", "\xF0\x9F\x94\xB7"},
    [":large_orange_diamond:"] = {"(diamond)", "\xF0\x9F\x94\xB6"},
    [":small_blue_diamond:"] = {"(diamond)", "\xF0\x9F\x94\xB9"},
    [":small_orange_diamond:"] = {"(diamond)", "\xF0\x9F\x94\xB8"},
    [":small_red_triangle:"] = {"(tri)", "\xF0\x9F\x94\xBA"},
    [":small_red_triangle_down:"] = {"(tri)", "\xF0\x9F\x94\xBB"},
    [":clock12:"] = {"(12)", "\xF0\x9F\x95\x9B"},
    [":clock3:"] = {"(3)", "\xF0\x9F\x95\x93"},
    [":clock6:"] = {"(6)", "\xF0\x9F\x95\x96"},
    [":clock9:"] = {"(9)", "\xF0\x9F\x95\x99"},
    [":hourglass:"] = {"(time)", "\xE2\x8F\xB3"},
    [":hourglass_flowing_sand:"] = {"(time)", "\xE2\x8F\xB3"},
    [":watch:"] = {"(time)", "\xE2\x8F\xB0"},
    [":alarm_clock:"] = {"(alarm)", "\xE2\x8F\xB0"},
    [":calendar:"] = {"(cal)", "\xF0\x9F\x93\x85"},
    [":date:"] = {"(date)", "\xF0\x9F\x93\x85"},
    [":mailbox:"] = {"(mail)", "\xF0\x9F\x93\xAB"},
    [":email:"] = {"(mail)", "\xE2\x9C\x89"},
    [":envelope:"] = {"(mail)", "\xE2\x9C\x89"},
    [":incoming_envelope:"] = {"(mail)", "\xF0\x9F\x93\xA8"},
    [":package:"] = {"(box)", "\xF0\x9F\x93\xA6"},
    [":bookmark:"] = {"(mark)", "\xF0\x9F\x94\x96"},
    [":label:"] = {"(label)", "\xF0\x9F\x8F\xB7"},
    [":key:"] = {"(key)", "\xF0\x9F\x94\x91"},
    [":lock:"] = {"(lock)", "\xF0\x9F\x94\x92"},
    [":unlock:"] = {"(unlock)", "\xF0\x9F\x94\x93"},
    [":wrench:"] = {"(wrench)", "\xF0\x9F\x94\xA7"},
    [":hammer:"] = {"(hammer)", "\xF0\x9F\x94\xA8"},
    [":nut_and_bolt:"] = {"(bolt)", "\xF0\x9F\x94\xA9"},
    [":gear:"] = {"(gear)", "\xE2\x9A\x99"},
    [":mag:"] = {"(search)", "\xF0\x9F\x94\x8D"},
    [":mag_right:"] = {"(search)", "\xF0\x9F\x94\x8E"},
    [":microscope:"] = {"(scope)", "\xF0\x9F\x94\xAC"},
    [":telescope:"] = {"(scope)", "\xF0\x9F\x94\xAD"},
    [":satellite:"] = {"(sat)", "\xF0\x9F\x93\xA1"},
    [":battery:"] = {"(bat)", "\xF0\x9F\x94\x8B"},
    [":electric_plug:"] = {"(plug)", "\xF0\x9F\x94\x8C"},
    [":bulb:"] = {"(idea)", "\xF0\x9F\x92\xA1"},
    [":flashlight:"] = {"(light)", "\xF0\x9F\x94\xA6"},
    [":candle:"] = {"(candle)", "\xF0\x9F\x95\xAF"},
    [":bathtub:"] = {"(bath)", "\xF0\x9F\x9B\x81"},
    [":shower:"] = {"(shower)", "\xF0\x9F\x9A\xBF"},
    [":toilet:"] = {"(wc)", "\xF0\x9F\x9A\xBD"},
    [":bell:"] = {"(bell)", "\xF0\x9F\x94\x94"},
    [":no_bell:"] = {"(no bell)", "\xF0\x9F\x94\x95"},
    [":bookmark:"] = {"(mark)", "\xF0\x9F\x94\x96"},
    [":book:"] = {"(book)", "\xF0\x9F\x93\x96"},
    [":books:"] = {"(books)", "\xF0\x9F\x93\x9A"},
    [":ledger:"] = {"(book)", "\xF0\x9F\x93\x92"},
    [":notebook:"] = {"(book)", "\xF0\x9F\x93\x93"},
    [":page_with_curl:"] = {"(page)", "\xF0\x9F\x93\x83"},
    [":scroll:"] = {"(scroll)", "\xF0\x9F\x93\x9C"},
    [":memo:"] = {"(memo)", "\xF0\x9F\x93\x9D"},
    [":pencil:"] = {"(pen)", "\xF0\x9F\x93\x9D"},
    [":pencil2:"] = {"(pen)", "\xE2\x9C\x8F"},
    [":black_nib:"] = {"(nib)", "\xE2\x9C\x92"},
    [":paintbrush:"] = {"(brush)", "\xF0\x9F\x96\x8C"},
    [":crayon:"] = {"(crayon)", "\xF0\x9F\x96\x8D"},
    [":briefcase:"] = {"(case)", "\xF0\x9F\x92\xBC"},
    [":file_folder:"] = {"(folder)", "\xF0\x9F\x93\x81"},
    [":open_file_folder:"] = {"(folder)", "\xF0\x9F\x93\x82"},
    [":card_index:"] = {"(card)", "\xF0\x9F\x97\x82"},
    [":chart_with_upwards_trend:"] = {"(up)", "\xF0\x9F\x93\x88"},
    [":chart_with_downwards_trend:"] = {"(down)", "\xF0\x9F\x93\x89"},
    [":bar_chart:"] = {"(chart)", "\xF0\x9F\x93\x8A"},
    [":clipboard:"] = {"(clip)", "\xF0\x9F\x93\x8B"},
    [":pushpin:"] = {"(pin)", "\xF0\x9F\x93\x8C"},
    [":round_pushpin:"] = {"(pin)", "\xF0\x9F\x93\x8D"},
    [":paperclip:"] = {"(clip)", "\xF0\x9F\x93\x8E"},
    [":link:"] = {"(link)", "\xF0\x9F\x94\x97"},
    [":paperclips:"] = {"(clip)", "\xF0\x9F\x96\x87"},
    [":triangular_ruler:"] = {"(ruler)", "\xF0\x9F\x93\x90"},
    [":straight_ruler:"] = {"(ruler)", "\xF0\x9F\x93\x8F"},
    [":scissors:"] = {"(cut)", "\xE2\x9C\x82"},

    -- Flags (common ones)
    [":flag-us:"] = {"(US)", "\xF0\x9F\x87\xBA\xF0\x9F\x87\xB8"},
    [":flag-es:"] = {"(ES)", "\xF0\x9F\x87\xAA\xF0\x9F\x87\xB8"},
    [":flag-mx:"] = {"(MX)", "\xF0\x9F\x87\xB2\xF0\x9F\x87\xBD"},
    [":flag-br:"] = {"(BR)", "\xF0\x9F\x87\xA7\xF0\x9F\x87\xB7"},
    [":flag-gb:"] = {"(GB)", "\xF0\x9F\x87\xAC\xF0\x9F\x87\xA7"},
    [":flag-de:"] = {"(DE)", "\xF0\x9F\x87\xA9\xF0\x9F\x87\xAA"},
    [":flag-fr:"] = {"(FR)", "\xF0\x9F\x87\xAB\xF0\x9F\x87\xB7"},
    [":flag-it:"] = {"(IT)", "\xF0\x9F\x87\xAE\xF0\x9F\x87\xB9"},
    [":flag-pt:"] = {"(PT)", "\xF0\x9F\x87\xB5\xF0\x9F\x87\xB9"},
    [":flag-ar:"] = {"(AR)", "\xF0\x9F\x87\xA6\xF0\x9F\x87\xB7"},
    [":flag-co:"] = {"(CO)", "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB4"},
    [":flag-cl:"] = {"(CL)", "\xF0\x9F\x87\xA8\xF0\x9F\x87\xB1"},
    [":flag-pe:"] = {"(PE)", "\xF0\x9F\x87\xB5\xF0\x9F\x87\xAA"},
    [":flag-ve:"] = {"(VE)", "\xF0\x9F\x87\xBB\xF0\x9F\x87\xAA"},
    [":flag-ec:"] = {"(EC)", "\xF0\x9F\x87\xAA\xF0\x9F\x87\xA8"},
    [":flag-uy:"] = {"(UY)", "\xF0\x9F\x87\xBA\xF0\x9F\x87\xBE"},
    [":flag-py:"] = {"(PY)", "\xF0\x9F\x87\xB5\xF0\x9F\x87\xBE"},
    [":flag-bo:"] = {"(BO)", "\xF0\x9F\x87\xA7\xF0\x9F\x87\xB4"},
    [":flag-ca:"] = {"(CA)", "\xF0\x9F\x87\xA8\xF0\x9F\x87\xA6"},

    -- Special
    [":shrug:"] = {"\\_(:/)_/", "\xF0\x9F\xA4\xB7"},
    [":facepalm:"] = {"(facepalm)", "\xF0\x9F\xA4\xA6"},
    [":shrug_tone1:"] = {"\\_(:/)_/", "\xF0\x9F\xA4\xB7\xF0\x9F\x8F\xBB"},
    [":shrug_tone2:"] = {"\\_(:/)_/", "\xF0\x9F\xA4\xB7\xF0\x9F\x8F\xBC"},
    [":shrug_tone3:"] = {"\\_(:/)_/", "\xF0\x9F\xA4\xB7\xF0\x9F\x8F\xBD"},
    [":shrug_tone4:"] = {"\\_(:/)_/", "\xF0\x9F\xA4\xB7\xF0\x9F\x8F\xBE"},
    [":shrug_tone5:"] = {"\\_(:/)_/", "\xF0\x9F\xA4\xB7\xF0\x9F\x8F\xBF"},
    [":table_flip:"] = {"(╯°□°)╯", "(╯°□°)╯"},
    [":this:"] = {"(this)", "\xF0\x9F\x91\x89"},
    [":that:"] = {"(that)", "\xF0\x9F\x91\x88"},
}

-- Build reverse lookup: unicode emoji -> shortcode
local UnicodeToShortcode = {}
for shortcode, data in pairs(DiscordEmojis) do
    local unicode = data[2]
    if unicode and #unicode > 0 then
        UnicodeToShortcode[unicode] = shortcode
    end
end

-- Convert Discord shortcodes (:smile:) to display format
-- Uses text emoticons by default, or Unicode if USE_UNICODE_EMOJIS is true
function discordEmojiFromShortcode(text)
    if not text then return text end
    local result = text
    for shortcode, data in pairs(DiscordEmojis) do
        local replacement = USE_UNICODE_EMOJIS and data[2] or data[1]
        if replacement then
            result = result:gsub(shortcode, replacement)
        end
    end
    return result
end

-- Convert Unicode emojis back to Discord shortcodes for sending to Discord
function discordEmojiToShortcode(text)
    if not text then return text end
    local result = text
    for unicode, shortcode in pairs(UnicodeToShortcode) do
        result = result:gsub(unicode, shortcode)
    end
    return result
end

-- Set emoji display mode (true = Unicode, false = text emoticons)
function setDiscordEmojiMode(useUnicode)
    USE_UNICODE_EMOJIS = useUnicode
end

-- Get current emoji mode
function getDiscordEmojiMode()
    return USE_UNICODE_EMOJIS
end
